workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      groups:
        - appstore_credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"                
        BUNDLE_ID: "com.example.kobitionIntegration"
        APP_STORE_ID: 1111111111 
        APPPATH: "build/ios/ipa/kobition_integration.ipa"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Flutter analyze
        script: |
          cd . && flutter analyze
      - name: Flutter unit tests
        script: |
          cd . && flutter test
        ignore_failure: true          
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --export-options-plist=/Users/builder/export_options.plist
      - name: Kobiton integration
        script: |
#       JSON="{\"filename\":\"*.ipa\",\"appPath\":\"/build/ios/ipa/kobition_integration.ipa\"}"
#       curl -X POST https://api.kobiton.com/v1/apps \
#       -H 'Authorization: Basic c0eb5ab4-3f3f-43c0-9325-1ea473349ca8' \
#       -H 'content-type: application/json' \
#       -d '$JSON'
          
          curl -X POST https://api.kobiton.com/v1/apps/uploadUrl \
          -H 'Authorization: Basic c0eb5ab4-3f3f-43c0-9325-1ea473349ca8' \
          -H 'Content-Type: application/json' \
          -H 'Accept: application/json'
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
