# 
workflows:
  android-fastlane:
    name: Android Fastlane
    instance_type: linux_x2
    environment:
      groups:
        - app_gallery # <-- (Includes CLIENT_ID, CLIENT_SECRET, APP_ID)
      android_signing:
        - android_signing
    scripts:
      - name: Gradlew
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"     
      - name: Publish to the AppGallery store
        script: | 
          cd android 
          gradle wrapper
          chmod +x gradlew 
      - name: Gradlew
        script: |
          fastlane add_plugin huawei_appgallery_connect
          bundle install
          bundle exec fastlane huawei
    artifacts:
      - app/build/outputs/**/**/*.aab