# 
workflows:
  android-fastlane:
    name: Android Fastlane
    instance_type: mac_mini_m1
    environment:
      groups:
        - app_gallery # <-- (Includes CLIENT_ID, CLIENT_SECRET, APP_ID)
      android_signing:
        - android_signing
    scripts:
      - name: Gradlew
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"  
          flutter pub get
      - name: Gradlew
        script: |
          cd android
          gradle wrapper
          chmod +x gradlew 
          fastlane add_plugin huawei_appgallery_connect
          bundle install
          bundle exec fastlane huawei
     artifacts:
      - /Users/builder/clone/build/app/outputs/bundle/release/app-release.aab