# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

lane :huawei do
  gradle(
    task: 'bundle', #apk & aab
    build_type: 'Release',
    print_command: true,
  )

  huawei_appgallery_connect(
  client_id: "#{ENV["CLIENT_ID"]}",
  client_secret: "#{ENV["CLIENT_SECRET"]}",
  app_id: "#{ENV["APP_ID"]}",
  apk_path: "./app/build/outputs/bundle/release/app-release.aab",

  # Optional, Parameter beyond this are optional
  is_aab: true,
  submit_for_review: true,
  delay_before_submit_for_review: 20,
)
end